#!/bin/sh

# Bump this when rebuilding with changes
TAG=20150617

if ! test -e .ssh/id_rsa
then
    echo "Please copy buildbot's github SSH key to .ssh/id_rsa"
    exit 1
fi
if ! test -e .s3cfg
then
    echo "Please copy buildbot's .s3cfg to .s3cfg"
    exit 1
fi

mkdir -p build

# Only copy this if it doesn't exist. Prevents re-running steps in
# this Dockerfile. This does mean that if you need to update the
# gcc, you need to manually delete this directory and rebuild.
if [ ! -d build/local ]
then
    docker run -v $(pwd)/build:/output ceejatec/opensuse-gcc-build:11.2 cp -a /usr/local /output
fi
docker build -t ceejatec/suse-11-couchbase-builddocker:$TAG .
docker tag -f ceejatec/suse-11-couchbase-builddocker:$TAG ceejatec/suse-11-couchbase-builddocker:latest

