---
# Create sg_accel user
- hosts: all
  any_errors_fatal: true
  become: yes
  tasks:
  - name: Create sync gateway user
    user: name=sg_accel createhome=yes

# Download sg_accel package
- hosts: all
  any_errors_fatal: true

  vars:
    couchbase_sg_accel_package_base_url:
    couchbase_sg_accel_package:
    couchbase_sg_accel_package_url: "{{ couchbase_sg_accel_package_base_url }}/{{ couchbase_sg_accel_package }}"

  tasks:
  - debug: msg="Downloading sg_accel v. {{ couchbase_sg_accel_package_url }}"
  - name: Download sg_accel rpm
    get_url: url={{ couchbase_sg_accel_package_url }} dest=/tmp/{{ couchbase_sg_accel_package }}

# Install and launch sg_accel service
- hosts: all
  any_errors_fatal: true
  become: yes
  tasks:
  # Install and start service.  Don't try to wait on the service to be listening on port 4985
  # because it's actually expected NOT to be able to run w/ the default config
  # See 
  - name: Install sg_accel rpm
    shell: rpm -i /tmp/{{ couchbase_sg_accel_package }}


