#!/bin/sh

RS=/home/gerrit/review_site
BUILD=/home/gerrit/build/gerrit

# patchset-created --change <change id> --change-url <change url>
#                  --project <project name> --branch <branch>
#                  --uploader <uploader> --commit <sha1>
#                  --patchset <patchset id>

while [ $# -gt 0 ]
do
    arg=$1
    shift

    case "$arg" in
	--change)
	    change=$1
	    ;;
	--change-url)
	    change_url=$1
	    ;;
	--project)
	    project=$1
	    ;;
	--branch)
	    branch=$1
	    ;;
	--submitter)
	    submitter=$1
	    ;;
	--uploader)
	    uploader=$1
	    ;;
	--commit)
	    commit=$1
	    ;;
	--patchset)
	    patchset=$1
	    ;;
	--is-draft)
	    is_draft=$1
	    ;;
	--kind)
	    kind=$1
	    ;;
	*)
	    echo "Unexpected arg:  $arg"
	    exit 1
	    ;;
    esac
    shift
done

exec >>$HOME/review_site/logs/hook.log 2>&1

echo =============================
echo "Patchset Created Hook (currently does nothing)"
echo "date: `date`"
echo "change: $change"
echo "change_url: $change_url"
echo "project: $project"
echo "branch: $branch"
echo "uploader: $uploader"
echo "submitter: $submitter"
echo "commit: $commit"
echo "patchset: $patchset"

