#!/bin/sh

if ! test -e .ssh/id_rsa
then
    echo "Please copy buildbot's github SSH key to .ssh/id_rsa"
    exit 1
fi
if ! test -e .s3cfg
then
    echo "Please copy buildbot's .s3cfg to .s3cfg"
    exit 1
fi
docker build -t ceejatec/centos-58-couchbase-builddocker .
