#!/bin/sh -ex

# Bump this when rebuilding with changes
TAG=20160125

mkdir -p build
cp -a -u ../../util/couchbuilder_start.sh build

# Only copy this if it doesn't exist. Prevents re-running steps in
# this Dockerfile. This does mean that if you need to update the
# gcc, you need to manually delete this directory and rebuild.
if [ ! -d build/local ]
then
    docker run -v $(pwd)/build:/output ceejatec/debian-gcc-build:7.6 cp -a /usr/local /output
fi
docker build --no-cache -t ceejatec/debian-7-couchbase-build-gcc49:$TAG .
docker tag -f ceejatec/debian-7-couchbase-build-gcc49:$TAG ceejatec/debian-7-couchbase-build-gcc49:latest
if [ "$1" = "--publish" ]
then
  docker push ceejatec/debian-7-couchbase-build-gcc49:$TAG
  docker push ceejatec/debian-7-couchbase-build-gcc49:latest
fi

