#!/bin/bash
distrib=`cat /etc/lsb-release | grep DISTRIB_CODENAME | awk -F= '{print $2}'`
if [ "$distrib" = "precise" -o "$distrib" = "trusty" -o "$distrib" = "lucid" -o "$distrib" = "wheezy" ]; then
    exit 0
fi
echo Supported platforms are: Debian/wheezy, Ubuntu/lucid,precise,trusty
echo
exit 1
