#!/bin/sh -ex

# Bump this when rebuilding with changes
TAG=$(date +%Y%m%d)
IMAGE=ceejatec/ubuntu-1604-couchbase-build

mkdir -p build
cp -a -u ../../util/couchbuilder_start.sh build

# Only copy this if it doesn't exist. Prevents re-running steps in
# this Dockerfile. This does mean that if you need to update the
# gcc, you need to manually delete this directory and rebuild.
# Note: the gcc build image is in build-infra.
if [ ! -d build/local ]
then
    docker run --rm -v $(pwd)/build:/output \
        couchbasebuild/ubuntu-1604-gcc:7.3.0 \
        cp -a /usr/local /output
fi
docker build -t ${IMAGE}:${TAG} .
docker tag ${IMAGE}:${TAG} ${IMAGE}:latest
if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:$TAG
  docker push ${IMAGE}:latest
fi
