#!/bin/sh

# Bump this when rebuilding with changes
TAG=20161214

docker build -t ceejatec/ubuntu-1204-couchbase-cv:$TAG .
docker tag ceejatec/ubuntu-1204-couchbase-cv:$TAG ceejatec/ubuntu-1204-couchbase-cv:latest
if [ "$1" = "--publish" ]
then
  docker push ceejatec/ubuntu-1204-couchbase-cv:$TAG
  docker push ceejatec/ubuntu-1204-couchbase-cv:latest
fi

