#!/bin/bash
#
# Common script run by various Jenkins builds to run CBNT testing on kv_engine

if [ -z "$GERRIT_HOST" ]; then
    echo "Error: Required environment variable 'GERRIT_HOST' not set."
    exit 1
fi
if [ -z "$GERRIT_PORT" ]; then
    echo "Error: Required environment variable 'GERRIT_PORT' not set."
    exit 2
fi
if [ -z "$GERRIT_PROJECT" ]; then
    echo "Error: Required environment variable 'GERRIT_PROJECT' not set."
    exit 3
fi
if [ -z "$GERRIT_PATCHSET_REVISION" ]; then
    echo "Error: Required environment variable 'GERRIT_PATCHSET_REVISION' not set."
    exit 4
fi
if [ -z "$GERRIT_REFSPEC" ]; then
    echo "Error: Required environment variable 'GERRIT_REFSPEC' not set."
    exit 5
fi
if [ -z "$GERRIT_CHANGE_ID" ]; then
    echo "Error: Required environment variable 'GERRIT_CHANGE_ID' not set."
    exit 6
fi
if [ -z "$WORKSPACE" ]; then
    echo "Error: Required environment variable 'WORKSPACE' not set."
    exit 7
fi
if [ -z "$LNT_IP" ]; then
    echo "Error: Required environment variable 'LNT_IP' not set."
    exit 8
fi
if [ "${GERRIT_PROJECT}" != "kv_engine" ]
    echo "Error: Project ${GERRIT_PROJECT} is not kv_engine"
    exit 9
fi

cd ${GERRIT_PROJECT}
git fetch http://${GERRIT_HOST}/${GERRIT_PROJECT} $GERRIT_REFSPEC
git checkout --force FETCH_HEAD
cd ..
mkdir -p build
cd build
cmake -DCOUCHBASE_KV_COMMIT_VALIDATION=1 ..
cd kv_engine
make -j24
cd ../..

# We run the lnt command under numactl --interleave=all
# this is due to the fact that before this, the tests were rather
# unstable in their execution times and had a large std. deviaiton
# even when running in the most determenistic way possible. After testing
# we found this to be the most stable way of running the tests to get repeatable
# results.
numactl --interleave=all lnt runtest kv-engine ${WORKSPACE}/kv_engine/tests/cbnt_tests/cbnt_test_list.yml\
 cv --submit_url=http://${LNT_IP}/submitRun -v --commit=1
