#!/bin/sh -e

# Bump this when rebuilding with changes
TAG=20170522

mkdir -p build
cp -a ../../util/couchbuilder_start.sh build
docker build -t ceejatec/centos-65-couchbase-build:$TAG .
docker tag ceejatec/centos-65-couchbase-build:$TAG ceejatec/centos-65-couchbase-build:latest
if [ "$1" = "--publish" ]
then
  docker push ceejatec/centos-65-couchbase-build:$TAG
  docker push ceejatec/centos-65-couchbase-build:latest
fi

