#!/bin/sh

# Bump this when rebuilding with changes
TAG=$(date "+%Y%m%d")

docker build --build-arg CONTAINER_TAG_ARG=ceejatec/ubuntu-1604-couchbase-cv:$TAG -t ceejatec/ubuntu-1604-couchbase-cv:$TAG .
docker tag ceejatec/ubuntu-1604-couchbase-cv:$TAG ceejatec/ubuntu-1604-couchbase-cv:latest
if [ "$1" = "--publish" ]
then
  docker push ceejatec/ubuntu-1604-couchbase-cv:$TAG
  docker push ceejatec/ubuntu-1604-couchbase-cv:latest
fi
