#!/bin/sh

# Bump this when rebuilding with changes
TAG=20151223

mkdir -p build
cp -a ../../util/couchbuilder_start.sh build
docker build -t ceejatec/ubuntu-1204-couchbase-build:$TAG .
docker tag -f ceejatec/ubuntu-1204-couchbase-build:$TAG ceejatec/ubuntu-1204-couchbase-build:latest
if [ "$1" = "--publish" ]
then
  docker push ceejatec/ubuntu-1204-couchbase-build:$TAG
  docker push ceejatec/ubuntu-1204-couchbase-build:latest
fi

