#!/bin/sh

mkdir -p build
cp -a -u ../../util/couchbuilder_start.sh build

# Only copy this if it doesn't exist. Prevents re-running steps in
# this Dockerfile. This does mean that if you need to update the
# gcc, you need to manually delete this directory and rebuild.
if [ ! -d build/local ]
then
    docker run -v $(pwd)/build:/output ceejatec/opensuse-gcc-build:latest cp -a /usr/local /output
fi
docker build -t ceejatec/opensuse-113-couchbase-build .
