#!/bin/sh -e

# Bump this when rebuilding with changes
TAG=$(date +%Y%m%d)
IMAGE=ceejatec/suse-11-couchbase-build

mkdir -p build
cp -a -u ../../util/couchbuilder_start.sh build

# Only copy this if it doesn't exist. Prevents re-running steps in
# this Dockerfile. This does mean that if you need to update the
# gcc, you need to manually delete this directory and rebuild.
if [ ! -d build/local ]
then
    docker run --rm -v $(pwd)/build:/output \
        couchbasebuild/suse-11-gcc:7.2.0 \
        cp -a /usr/local /output
fi
docker build -t ${IMAGE}:${TAG} .
docker tag ${IMAGE}:${TAG} ${IMAGE}:latest

if [ "$1" = "--publish" ]
then
    docker push ${IMAGE}:$TAG
    docker push ${IMAGE}:latest
fi
