#!/bin/sh

# Bump this when rebuilding with changes
TAG=20150617

mkdir -p build
cp -a -u ../../util/couchbuilder_start.sh build

# Only copy this if it doesn't exist. Prevents re-running steps in
# this Dockerfile. This does mean that if you need to update the
# gcc, you need to manually delete this directory and rebuild.
if [ ! -d build/local ]
then
    docker run -v $(pwd)/build:/output ceejatec/opensuse-gcc-build:11.2 cp -a /usr/local /output
fi
docker build -t ceejatec/suse-11-couchbase-build:$TAG .
docker tag -f ceejatec/suse-11-couchbase-build:$TAG ceejatec/suse-11-couchbase-build:latest

