#!/bin/sh

set -e
set -x

curdir=`dirname $0`

# CCACHE is good - use it if available.
export PATH=/usr/lib/ccache:$PATH


cat <<EOF
============================================
===              environment             ===
============================================
EOF
ulimit -a
env | grep -iv password | grep -iv passwd | sort

cat <<EOF
============================================
===                 clean                ===
============================================
EOF
make clean-xfd-hard

cat <<EOF
============================================
===       update all projects with       ===
===          the same Change-Id          ===
============================================
EOF
${curdir}/../checkout_dependencies.py $GERRIT_PATCHSET_REVISION $GERRIT_CHANGE_ID $GERRIT_PROJECT $GERRIT_REFSPEC

cat <<EOF
============================================
===                 build                ===
============================================
EOF
make -j4

cat <<EOF
============================================
===       run viewmerge.conf tests       ===
============================================
EOF
cd testrunner
scripts/start_cluster_and_run_tests.sh b/resources/dev-single-node.ini conf/view-conf/py-viewmerge.conf
scripts/start_cluster_and_run_tests.sh b/resources/dev-4-nodes.ini conf/view-conf/py-viewmerge.conf
cd ..
