#!/bin/sh

# Bump this when rebuilding with changes
#TAG=`date +%Y%m%d`
TAG=20160712

mkdir -p build
cp -a ../../util/couchbuilder_start.sh build
docker build -t ceejatec/ubuntu1404-mobile-android-docker:$TAG .
