#!/bin/sh -e

# Bump this when rebuilding with changes
TAG=20170613

# Image name
IMAGE=couchbase/centos-72-java-sdk

docker build -t ${IMAGE}:$TAG .
docker tag ${IMAGE}:$TAG ${IMAGE}:latest

if [ "$1" = "--publish" ]
then
    docker push ${IMAGE}:$TAG
    docker push ${IMAGE}:latest
fi

