#!/bin/sh

# Bump this when rebuilding with changes
TAG=20160208

mkdir -p build
cp -a ../../util/couchbuilder_start.sh build
docker build -t couchbase/centos-70-sdk-build:$TAG .
docker tag -f couchbase/centos-70-sdk-build:$TAG couchbase/centos-70-sdk-build:latest
if [ "$1" = "--publish" ]
then
  docker push couchbase/centos-70-sdk-build:$TAG
  docker push couchbase/centos-70-sdk-build:latest
fi
