#!/bin/sh

# Bump this when rebuilding with changes
TAG=`date +%Y%m%d`
IMAGE=couchbasebuild/ubuntu1604-mobile-lite-android

mkdir -p build
cp -a ../../util/couchbuilder_start.sh build
docker build -t ${IMAGE}:$TAG .
docker tag ${IMAGE}:$TAG ${IMAGE}:latest
if [ "$1" = "--publish" ]
then
    docker push ${IMAGE}:$TAG
    docker push ${IMAGE}:latest
fi
