#!/bin/bash
gpg --import /etc/apt/trusted.gpg.d/GPG-KEY-COUCHBASE-1.0
apt-key add /etc/apt/trusted.gpg.d/GPG-KEY-COUCHBASE-1.0

repl=`lsb_release -c | awk '{print $2}'`
sed -e "s/%DCODE%/$repl/g" -i /etc/apt/sources.list.d/couchbase.list
