#!/bin/bash
gpg --import /etc/apt/trusted.gpg.d/GPG-KEY-COUCHBASE-1.0
apt-key add /etc/apt/trusted.gpg.d/GPG-KEY-COUCHBASE-1.0

repl=`lsb_release -c | awk '{print $2}'`
if [ "$repl" = "precise" -o "$repl" = "trusty" -o "$repl" = "xenial" -o "$repl" = "lucid" -o "$repl" = "wheezy" -o "$repl" = "jessie" ]; then
    sed -e "s/%DCODE_SERVER%/$repl/g" -i /etc/apt/sources.list.d/couchbase.list
    sed -e "s/%DCODE_SDK%/$repl/g" -i /etc/apt/sources.list.d/couchbase.list
fi
